apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rundeck
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/diegofnunesbr/rundeck.git
    targetRevision: main
    path: .
    directory:
      include: "{rundeck.yaml,rundeck-realm.sealed.yaml,rundeck-oidc.sealed.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: rundeck
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
